apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: api-service-redis
  namespace: novadeploy
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: api-service-redis-credentials
    creationPolicy: Owner
  data:
    - secretKey: host
      remoteRef:
        key: dev/api-service/redis
        property: host
    - secretKey: port
      remoteRef:
        key: dev/api-service/redis
        property: port
    - secretKey: password
      remoteRef:
        key: dev/api-service/redis
        property: password
