apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - secret-store.yaml
  - external-secret-api-db.yaml
  - external-secret-api-redis.yaml
  - external-secret-worker-db.yaml
  - external-secret-worker-redis.yaml
  - external-secret-database.yaml
