# Vault token secret for ESO to authenticate
apiVersion: v1
kind: Secret
metadata:
  name: vault-token
  namespace: novadeploy
type: Opaque
stringData:
  token: root
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: novadeploy
spec:
  provider:
    vault:
      server: "http://vault.vault.svc:8200"
      path: "secret"
      version: "v2"
      auth:
        tokenSecretRef:
          name: vault-token
          key: token
